server:
  port: 9006

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://localhost:3306/review?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.reviewservice.model

auth-service:
  url: "${AUTH_SERVICE_URL:http://localhost:9002}"

order-service:
  url: "${ORDER_SERVICE_URL:http://localhost:9004}"

jwt:
  issuer: dlstlr1707@gmail.com
  secret_key: 55DQ7XtZjKEuftetbQMtw0geU9SS1rR/fbrPOAqIQ2UUPJ+crjXRoLppDtreyvim53v3U6+hTLcbunHlxlNGlA==